als/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('muskers.urls')),
    path('', include('shortener.urls')),
]

muskers/urls.py
from django.urls import path

from . import views

app_name = 'muskers'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('user/', views.CreateCulinkView.as_view(), name='user'),
    path('user/shorts/', views.ResultsView.as_view(), name='shorts'),
    path('user/shorts/details/<slug:slug>/', views.CulinkDetailsView.as_view(), name='details'),
    path('user/shorts/edit/<slug:slug>/', views.CulinkUpdateView.as_view(), name='edit'),
    path('user/shorts/delete/<slug:slug>/', views.CulinkDeleteView.as_view(), name='delete'),
    path('user/settings/', views.UserUpdateView.as_view(), name='settings'),
    path('user/settings/password/', views.UserPasswordView.as_view(), name='password'),
    path('user/settings/delete/<slug:slug>/', views.UserDeleteView.as_view(), name='delete_user')
]

shortener/urls.py
from django.urls import path

from . import views

app_name = 'shortener'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('r/<str:shortlink>/', views.check_link),
    path('<str:shortlink>/', views.redirect_to)
]

templates/base.html
<!DOCTYPE HTML>

<html lang="en">

<head>

	<meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="als, shortener, url, link, urls, links"/>
	<meta name="description" content="Save your valiable time by shortening links."/>

	<title>ALS the URL shortener</title>

	{% load static %}
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	{% block stylelink %}{% endblock %}

</head>

<body>
	<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'shortener:index' %}">ALS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
				{% if user.is_authenticated %}
				<li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'muskers:user' %}">MAKE SHORTCUTS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'muskers:shorts' %}">VIEW SHORTCUTS</a>
        </li>
				{% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shortener:index' %}">MAIN PAGE</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shortener:about' %}">ABOUT</a>
        </li>
				{% endif %}
      </ul>
			{% if user.is_authenticated %}
      <form class="d-flex" action="{% url 'muskers:settings' %}" method="get">
				{% csrf_token %}
        <button class="btn btn-outline-primary" type="submit">SETTINGS</button>
      </form>
			<form class="d-flex" action="{% url 'muskers:logout' %}" method="get">
				{% csrf_token %}
        <button class="btn btn-primary" type="submit">SIGN OUT</button>
      </form>
			{% else %}
			<form class="d-flex" action="{% url 'muskers:register' %}" method="get">
				{% csrf_token %}
        <button class="btn btn-outline-primary" type="submit">SIGN UP</button>
      </form>
			<form class="d-flex" action="{% url 'muskers:index' %}" method="get">
				{% csrf_token %}
        <button class="btn btn-primary" type="submit">SIGN IN</button>
      </form>
			{% endif %}
    </div>
  </div>
</nav>

	<div class="container text-center">

		<main>

			<header>

				{% block myjumbotron %} {% endblock %}

			</header>

			<section>

				{% block content %} {% endblock %}

			</section>

		</main>

		<article>

			{% block marticle %} {% endblock %}

		</article>

		<footer class="py-5">
			By using our service you accept the <a class="text-decoration-none" href="">Terms of service</a>
			2021 &copy; All rights reserved!
		</footer>

	</div>

</body>

</html>