als/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('muskers.urls')),
    path('', include('shortener.urls')),
]

muskers/urls.py
from django.urls import path

from . import views

app_name = 'muskers'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('user/', views.CreateCulinkView.as_view(), name='user'),
    path('user/shorts/', views.ResultsView.as_view(), name='shorts'),
    path('user/shorts/details/<slug:slug>/', views.CulinkDetailsView.as_view(), name='details'),
    path('user/shorts/edit/<slug:slug>/', views.CulinkUpdateView.as_view(), name='edit'),
    path('user/shorts/delete/<slug:slug>/', views.CulinkDeleteView.as_view(), name='delete'),
    path('user/settings/', views.UserUpdateView.as_view(), name='settings'),
    path('user/settings/password/', views.UserPasswordView.as_view(), name='password'),
    path('user/settings/delete/<slug:slug>/', views.UserDeleteView.as_view(), name='delete_user')
]

muskers/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Culink(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    longlink_text = models.URLField(max_length=255)
    shortlink_text = models.SlugField(max_length=32, unique=True)
    creation_date = models.DateTimeField('creation date', auto_now_add=True)
    expiration_date = models.DateTimeField('expiration date', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('muskers:shorts')


class CulinkStat(models.Model):
    culink = models.ForeignKey(Culink, on_delete=models.CASCADE)
    creation_day = models.DateField('creation day', auto_now_add=True, unique=True)
    redirections = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return f"{self.creation_day}-{self.redirections}"

muskers/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Culink

class CulinkForm(forms.ModelForm):
    class Meta:
        model = Culink
        fields = ['shortlink_text', 'longlink_text']
        labels = {'shortlink_text' : '', 'longlink_text' : ''}
        widgets = {'shortlink_text' : forms.TextInput(attrs={'required' : True,
        'placeholder' : 'Type your shortcut', 'minlength' : 6, 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}),
            'longlink_text' : forms.URLInput(attrs={'required' : True,
            'placeholder' : 'Paste your link to shorten', 'minlength' : 15, 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'})}


class CulinkOneForm(forms.ModelForm):
    class Meta:
        model = Culink
        fields = ['longlink_text']
        labels = {'longlink_text' : ''}
        widgets = {'longlink_text' : forms.URLInput(attrs={'required' : True,
            'placeholder' : 'Paste your link to shorten', 'minlength' : 15, 'class': 'form-control border border-primary border-3 rounded-3'})}


class CulinkCheckOneForm(forms.ModelForm):
    class Meta:
        model = Culink
        fields = ['shortlink_text']
        labels = {'shortlink_text' : ''}
        widgets = {'shortlink_text' : forms.TextInput(attrs={'required' : True,
            'placeholder' : 'Type your link to check', 'minlength' : 6, 'class': 'form-control border border-primary border-3 rounded-3'})}


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='',
        widget=forms.TextInput(attrs={'placeholder' : 'Username', 'minlength' : 6, 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))
    password = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={'placeholder' : 'Password', 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='',
        widget=forms.TextInput(attrs={'placeholder' : 'Username', 'minlength' : 6, 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))
    password1 = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={'placeholder' : 'Password', 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))
    password2 = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={'placeholder' : 'Password', 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))


class PasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={'placeholder' : 'Old Password', 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))
    new_password1 = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={'placeholder' : 'New Password', 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))
    new_password2 = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={'placeholder' : 'New Password', 'class': 'my-2 fs-5 form-control border border-primary border-3 rounded-3'}))

muskers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

from django.contrib.auth.models import User

from .models import Culink, CulinkStat
from .forms import CulinkForm, LoginForm, RegisterForm, PasswordForm


class IndexView(LoginView):
    template_name = 'muskers/index.html'
    authentication_form = LoginForm
    redirect_field_name = 'muskers:user'
    redirect_authenticated_user = True


@method_decorator(login_required, name='dispatch')
class CreateCulinkView(PermissionRequiredMixin, FormView):
    permission_required = 'muskers.add_culink'
    template_name = 'muskers/user.html'
    form_class = CulinkForm
    success_url = 'shorts/'

    def shorten_by_user(self, tuser, longl, shortl):
        new_entry = Culink.objects.create(owner=tuser,
        longlink_text=longl, shortlink_text=shortl)

    def form_valid(self, form):
        longl = self.request.POST['longlink_text']
        shortl = self.request.POST['shortlink_text']
        tuser = self.request.user

        self.shorten_by_user(tuser, longl, shortl)

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class CulinkUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'muskers.change_culink'
    template_name = 'muskers/edit.html'
    model = Culink
    form_class = CulinkForm
    slug_field = "shortlink_text"

    def has_permission(self):
        culink_obj = self.get_object()

        if self.request.user == culink_obj.owner:
            perms = self.get_permission_required()
            return self.request.user.has_perms(perms)
        else:
            return False


@method_decorator(login_required, name='dispatch')
class CulinkDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'muskers.delete_culink'
    template_name = 'muskers/delete.html'
    model = Culink
    success_url = reverse_lazy('muskers:shorts')
    slug_field = "shortlink_text"

    def has_permission(self):
        culink_obj = self.get_object()

        if self.request.user == culink_obj.owner:
            perms = self.get_permission_required()
            return self.request.user.has_perms(perms)
        else:
            return False


@method_decorator(login_required, name='dispatch')
class ResultsView(PermissionRequiredMixin, ListView):
    permission_required = 'muskers.view_culink'
    template_name = 'muskers/shorts.html'
    model = Culink

    def get_context_data(self):
        culinks = Culink.objects.filter(owner=self.request.user)
        culinksDesc = culinks.order_by('-creation_date')

        paginator = Paginator(culinksDesc, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {'page_obj': page_obj}

        return context


@method_decorator(login_required, name='dispatch')
class CulinkDetailsView(PermissionRequiredMixin, DetailView):
    permission_required = 'muskers.view_culinkstat'
    template_name = 'muskers/charts.html'
    model = Culink
    slug_field = "shortlink_text"

    def has_permission(self):
        culink_obj = self.get_object()

        if self.request.user == culink_obj.owner:
            perms = self.get_permission_required()
            return self.request.user.has_perms(perms)
        else:
            return False

    def get(self, request, slug):
        culink = get_object_or_404(Culink, shortlink_text=slug, owner=request.user)
        culinkStats = CulinkStat.objects.filter(culink=culink)
        context = {'culink': culink, 'qs': culinkStats}

        return render(request, 'muskers/charts.html', context)


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('shortener:index'))


class UserCreateView(CreateView):
    template_name = 'muskers/register.html'
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('muskers:user')

    def get_success_url(self):
        user = self.object

        user_content_type = ContentType.objects.get_for_model(User)
        user_perms = Permission.objects.filter(content_type=user_content_type)
        culink_content_type = ContentType.objects.get_for_model(Culink)
        culink_perms = Permission.objects.filter(content_type=culink_content_type)

        view_culinkstat_perm = Permission.objects.get(codename='view_culinkstat')
        add_user_perm = Permission.objects.get(codename='add_user')

        for perm in user_perms:
            user.user_permissions.add(perm)
        for perm in culink_perms:
            user.user_permissions.add(perm)

        user.user_permissions.remove(add_user_perm)
        user.user_permissions.add(view_culinkstat_perm)

        if not self.success_url:
            raise ImproperlyConfigured("No URL to redirect to. Provide a success_url.")
        return str(self.success_url)


@method_decorator(login_required, name='dispatch')
class UserUpdateView(PermissionRequiredMixin, DetailView):
    permission_required = 'auth.change_user'
    template_name = 'muskers/settings.html'

    def get(self, request):
        return render(request, 'muskers/settings.html')


@method_decorator(login_required, name='dispatch')
class UserPasswordView(PermissionRequiredMixin, PasswordChangeView):
    permission_required = 'auth.change_user'
    template_name = 'muskers/password.html'
    form_class = PasswordForm
    success_url = reverse_lazy('muskers:settings')


@method_decorator(login_required, name='dispatch')
class UserDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'auth.delete_user'
    template_name = 'muskers/delete_user.html'
    model = User
    success_url = reverse_lazy('muskers:index')
    slug_field = "username"

    def has_permission(self):
        if self.request.user == self.get_object():
            perms = self.get_permission_required()
            return self.request.user.has_perms(perms)
        else:
            return False

muskers/templates/muskers/charts.html
{% extends "base.html" %}

{% block stylelink %}
{% load static %}
<script src="{% static 'muskers/js/chart.min.js' %}"></script>
{% endblock %}

{% block content %}
<div class="py-5">
<canvas id="myChart" width="400" height="200"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: [{% for item in qs %}'{{ item.creation_day }}',{% endfor %}],
      datasets: [{
        label: 'Redirections',
        data: [{% for item in qs %}{{ item.redirections }},{% endfor %}],
        backgroundColor: 'rgba(0, 81, 255, 0.2)',
        borderColor: 'rgba(0, 81, 255, 1)',
        borderWidth: 1,
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      }
    }
});
</script>
</div>
{% endblock %}

muskers/templates/muskers/delete.html
{% extends "base.html" %}

{% block content %}

{% if user == culink.owner %}

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<form class="col-md-4 mx-auto my-5 py-5" action="{% url 'muskers:delete' culink.shortlink_text %}" method="post">
		{% csrf_token %}

		<input class="my-2 fs-5 form-control border border-primary border-3 rounded-3 btn btn-primary" type="submit" value="Delete">

	</form>

{% else %}

You are not allowed!!!!
{{ culink.owner }}
{{ user }}

{% endif %}

{% endblock %}

muskers/templates/muskers/delete_user.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<form class="col-md-4 mx-auto my-5 py-5" action="{% url 'muskers:delete_user' user.username %}" method="post">
		{% csrf_token %}

		<input class="my-2 fs-5 form-control border border-primary border-3 rounded-3 btn btn-primary" type="submit" value="Delete">

	</form>

{% endif %}

{% endblock %}

muskers/templates/muskers/details.html
{% extends "base.html" %}

{% block content %}

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<div class="account_info">
		<table>
			<tr>
				<th>Shortcut Statistics</th>
			</tr>
			{% if chart %}
				<tr>
					<img src="data:image/png;base64, {{chart|safe}}">
				</tr>
			{% endif %}
			{% for stat in culinkStats %}
			<tbody>
				<tr>
					<td>{{ stat.creation_day }}</td>
					<td>{{ stat.redirections }}</td>
				</tr>
			</tbody>
			{% endfor %}
		</table>
	</div>

{% endif %}
{% endblock %}

muskers/templates/muskers/edit.html
{% extends "base.html" %}

{% block content %}

{% if user == culink.owner %}

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<form class="col-md-4 mx-auto my-5 py-5" action="{% url 'muskers:edit' culink.shortlink_text %}" method="post">
		{% csrf_token %}
		{{ form }}

		<input class="my-2 fs-5 form-control border border-primary border-3 rounded-3 btn btn-primary" type="submit" value="Save">

	</form>

{% else %}

You are not allowed!!!!
{{ culink.owner }}
{{ user }}

{% endif %}

{% endblock %}

muskers/templates/muskers/index.html
{% extends "base.html" %}

{% block content %}

<form class="col-md-4 mx-auto my-5 py-5" action="{% url 'muskers:index' %}" method="post">
	{% csrf_token %}
	{{ form }}

	<input class="my-2 fs-5 form-control border border-primary border-3 rounded-3 btn btn-primary" type="submit" value="Log in"/>
	<input type="hidden" name="next" value="{% url 'muskers:user' %}"/>

</form>

{% endblock %}

muskers/templates/muskers/password.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<form class="col-md-4 mx-auto my-5 py-5" action="{% url 'muskers:password' %}" method="post">
		{% csrf_token %}
		{{ form }}

		<input class="my-2 fs-5 form-control border border-primary border-3 rounded-3 btn btn-primary" type="submit" value="Change"/>

	</form>

{% endif %}
{% endblock %}

muskers/templates/muskers/register.html
{% extends "base.html" %}

{% block content %}
<form class="col-md-4 mx-auto my-5 py-5" action="{% url 'muskers:register' %}" method="post">
	{% csrf_token %}
	{{ form }}

	<input class="my-2 fs-5 form-control border border-primary border-3 rounded-3 btn btn-primary" type="submit" value="Register"/>
	<input type="hidden" name="next" value="{% url 'muskers:user' %}"/>

</form>
{% endblock %}

muskers/templates/muskers/settings.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<div class="table-responsive py-5">
		<table class="table table-borderless text-start">
			<thead>
			<tr>
				<th scope="col">Account information : </th>
			</tr>
			</thead>
			<tbody>
				<tr>
					<td>Username : </td>
					<td>{{ user.username }}</td>
				</tr>
				<tr>
					<td>Password : </td>
					<td>
						<a class="text-decoration-none" href="{% url 'muskers:password' %}">
							change
						</a>
					</td>
				</tr>
				<tr>
					<td>Date joined : </td>
					<td>{{ user.date_joined }}</td>
				</tr>
			</tbody>
		</table>
	</div>

	<a class="text-decoration-none" href="{% url 'muskers:delete_user' user.username %}">
		Delete Account
	</a>
{% endif %}
{% endblock %}

muskers/templates/muskers/shorts.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="table-responsive py-5">
	<table class="table table-borderless text-start">
		<thead class="">
			<tr class="">

				<th scope="col" class="">
					Shortcut
				</th>

				<th scope="col" class="">
					Destination
				</th>

			</tr>
		</thead>
		{% for link in page_obj %}
		<tbody class="">
			<tr class="">

				<th scope="row" class="">
					{{ link.shortlink_text|truncatechars:16 }}
				</th>

				<td class="">
					{{ link.longlink_text|truncatechars:32 }}
				</td>

				<td class="">
					<a class="text-decoration-none" href="{% url 'muskers:details' link.shortlink_text %}">DETAILS</a>
					<a class="text-decoration-none" href="{% url 'muskers:edit' link.shortlink_text %}">EDIT</a>
					<a class="text-decoration-none" href="{% url 'muskers:delete' link.shortlink_text %}">DELETE</a>
				</td>

			</tr>
		</tbody>
		{% endfor %}
	</table>
</div>

<div class="col-md-4 mx-auto border border-3">
<div class="pagination">
    <span class="step-links mx-auto">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>

{% endif %}
{% endblock %}

muskers/templates/muskers/user.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<form class="col-md-4 mx-auto my-5 py-5" action="{% url 'muskers:user' %}" method="post">
		{% csrf_token %}
		{{ form }}

		<input class="my-2 fs-5 form-control border border-primary border-3 rounded-3 btn btn-primary" type="submit" value="Shorten"/>

	</form>

{% endif %}
{% endblock %}